apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: awxprojects.wolkenzentrale.de
spec:
  group: wolkenzentrale.de
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - name
                - scmType
                - scmUrl
                - awxConnectionRef
              properties:
                awxConnectionRef:
                  type: object
                  required:
                    - name
                  properties:
                    name:
                      type: string
                      description: "Name of the AwxConnection resource"
                    namespace:
                      type: string
                      description: "Namespace of the AwxConnection resource. If not specified, defaults to the same namespace as this resource."
                  description: "Reference to the AwxConnection resource for this project"
                name:
                  type: string
                  description: "The name of the AWX project"
                description:
                  type: string
                  description: "Description of the AWX project"
                scmType:
                  type: string
                  description: "The SCM type for the project (git, svn, etc.)"
                scmUrl:
                  type: string
                  description: "The SCM URL for the project"
                scmBranch:
                  type: string
                  description: "The SCM branch for the project"
            status:
              type: object
              properties:
                # Base ResourceStatus fields
                message:
                  type: string
                  description: "Informational message about the current status"
                firstSuccessfulSync:
                  type: string
                  format: date-time
                  description: "Time when the resource was first successfully synchronized"
                lastUpdateTime:
                  type: string
                  format: date-time
                  description: "Time of the last status update"
                observedGeneration:
                  type: integer
                  description: "The resource generation that this status reflects"
                phase:
                  type: string
                  description: "Current phase of the resource (Pending, Running, Succeeded, Failed, Unknown)"
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                        description: "Type of the condition"
                      status:
                        type: string
                        description: "Status of the condition (True, False, Unknown)"
                      lastTransitionTime:
                        type: string
                        format: date-time
                        description: "Last time the condition status changed"
                      lastUpdateTime:
                        type: string
                        format: date-time
                        description: "Last time the condition was updated"
                      reason:
                        type: string
                        description: "Machine-readable reason for the condition's status"
                      message:
                        type: string
                        description: "Human-readable message about the condition"
                
                # AwxProjectStatus specific fields
                awxId:
                  type: integer
                  description: "The ID of the project in AWX"
                created:
                  type: string
                  format: date-time
                  description: "When the project was created in AWX"
                modified:
                  type: string
                  format: date-time
                  description: "When the project was last modified in AWX"
                status:
                  type: string
                  description: "The project status as reported by AWX"
                lastUpdateJobTime:
                  type: string
                  format: date-time
                  description: "Last time a project update was initiated"
                lastUpdateJobId:
                  type: integer
                  description: "ID of the last update job in AWX"
      additionalPrinterColumns:
        - name: Phase
          type: string
          jsonPath: .status.phase
        - name: Status
          type: string
          jsonPath: .status.status
        - name: AWX ID
          type: integer
          jsonPath: .status.awxId
        - name: Connection
          type: string
          jsonPath: .spec.awxConnectionRef.name
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: awxprojects
    singular: awxproject
    kind: AwxProject
    shortNames:
      - awxp 