apiVersion: wolkenzentrale.de/v1alpha1
kind: AwxProject
metadata:
  name: example-project
  namespace: default
spec:
  awxConnectionRef:
    name: my-awx
    # namespace: default  # Optional: defaults to same namespace as this resource
  name: "Example Project"
  description: "An example Ansible project managed by the AWX Operator"
  scmType: "git"
  scmUrl: "https://github.com/example/ansible-playbooks.git"
  scmBranch: "main" 