apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: awxinstances.wolkenzentrale.de
spec:
  group: wolkenzentrale.de
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - url
                - username
                - passwordSecretName
                - passwordSecretKey
              properties:
                url:
                  type: string
                  description: "The URL of the AWX instance"
                username:
                  type: string
                  description: "The username for authenticating with the AWX instance"
                passwordSecretName:
                  type: string
                  description: "The name of the secret containing the password"
                passwordSecretKey:
                  type: string
                  description: "The key in the secret that contains the password"
                insecureSkipTlsVerify:
                  type: boolean
                  description: "Whether to skip TLS verification"
            status:
              type: object
              properties:
                connectionStatus:
                  type: string
                  description: "The current connection status to the AWX instance"
                message:
                  type: string
                  description: "Informational message about the connection status"
                lastConnected:
                  type: string
                  description: "Timestamp of last successful connection"
      additionalPrinterColumns:
        - name: URL
          type: string
          jsonPath: .spec.url
        - name: Status
          type: string
          jsonPath: .status.connectionStatus
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: awxinstances
    singular: awxinstance
    kind: AwxInstance
    shortNames:
      - awxi 