apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: awxprojects.wolkenzentrale.de
spec:
  group: wolkenzentrale.de
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - name
                - scmType
                - scmUrl
              properties:
                name:
                  type: string
                  description: "The name of the AWX project"
                description:
                  type: string
                  description: "Description of the AWX project"
                scmType:
                  type: string
                  description: "The SCM type for the project (git, svn, etc.)"
                scmUrl:
                  type: string
                  description: "The SCM URL for the project"
                scmBranch:
                  type: string
                  description: "The SCM branch for the project"
            status:
              type: object
              properties:
                awxId:
                  type: integer
                  description: "The ID of the project in AWX"
                created:
                  type: string
                  format: date-time
                  description: "The creation timestamp"
                modified:
                  type: string
                  format: date-time
                  description: "The last modification timestamp"
                status:
                  type: string
                  description: "The current status of the project"
                message:
                  type: string
                  description: "Informational message about the project status"
      additionalPrinterColumns:
        - name: Status
          type: string
          jsonPath: .status.status
        - name: AWX ID
          type: integer
          jsonPath: .status.awxId
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: awxprojects
    singular: awxproject
    kind: AwxProject
    shortNames:
      - awxp 